# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1660880dd355b6a7348bf94fadf245752488a3c56f74439b36bee3319dba9909496b9f38f89e0dc95b2e23ef241b24df4217996bd8986bc391603ef831439c37

test:
  secret_key_base: 91bbe2e4e79a3cb82de7c65fcef474382041f9aa2c9cfdcb323ef9da835e38deec4b7a5aa459bbc1864c8662ac4c0f540cd00a329f1ecfddfd0ddc8006fc75e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 5dbcf3d0e9cc62dbb94667b55ed03b264dd00127d00b321c88b1ad2623658cdd665024c3d9af413d02413157d0b91e8b2458d0ca7f507349f75280735494a1d7
