# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 743e90cd91103ab304804b5923508377b7c20ec160a1d105a24cd1aeb03abcaaf8f2ade34a0e561bf0ffc43784f1b250ab6f8449ef6f1468ad914989092c542d

test:
  secret_key_base: 192c32e4cc7881bca57f9fc2396318f57dd95fa4c37ea9c677e531de4e0b501d2d27567dd39079c10a6a5090c076c151c2a7a89d5b0bc5e261ea1f71a961ecde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
