en:
  domain: yii.im

  html:
    title: yii.im
    keywords: Rails,Ruby,Sass,bootstrap
    description: Just a worm, seek for true, live in shadow, no more...

  email:
    default: yiichou@gmail.com
    smtp:
      host: smtp.gmail.com
      port: 587 
      user_name: yiichou
      password: 'goaweplz'

  socials:
    twitter: iamichou
    github: ivanchou
    google_plus: 106025147843011494846
    facebook: ichou.cn

  google_analytics:
    account: UA-57408564-1
    domain: yii.im

  aliyun_oss:
    access_id: MIpSAKlWwWF8XfX9
    access_key: wfPPyRqRcgkzwLilNxn7jpVk1jbhyL
    bucket: chou
    stc: stc.ichou.cn
    img: img.ichou.cn
