en:
  domain: yii.im
  session_key: _yii_im_session_mem_cache_secure

  memcache:
    servers:
      - 127.0.0.1
    options:
      namespace: _yii_im_cache_dalli
      expires_in: <%= 1.day %>
      compress: true

  html:
    title: yii.im
    keywords: Rails,Ruby,Sass,bootstrap
    description: Just a worm, seek for true, live in shadow, no more...

  email:
    default: yiichou@gmail.com
    smtp:
      host: smtp.gmail.com
      port: 587 
      user_name: yiichou
      password: 'goaweplz'

  socials:
    twitter: iamichou
    github: ivanchou
    google_plus: 106025147843011494846
    facebook: ichou.cn

  google_analytics:
    account: UA-57408564-1
    domain: yii.im
